export const QuizData = [
    {
        id: 1,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
    {
        id: 2,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
    {
        id: 3,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
    {
        id: 4,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
    {
        id: 5,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
    {
        id: 6,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
    {
        id: 7,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
    {
        id: 8,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
    {
        id: 9,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
    {
        id: 10,
        leftBannerText: "Strategic Business Planning",
        heading: "Statement of readiness",
        question: "We have written 2-3 strategic plan with clear objectives and financial targets. We have a Business Plan for this year execution & reviews are a part of our life",
        optionOne: "Yes, we do have Business plans & work as per the objectives",
        optionTwo: "Yes, we do have Business plans & work as per the objectives",
        optionThree: "Yes, we do have Business plans & work as per the objectives",
    },
]

//export default quizData;